### ISSUE TITLE
Something wrong at beginner level 2

### ISSUE THREAD

**Issue by liubiantao** [arbylee/python-warrior#2]
```
 (py)liubiantao@liubiantao-ThinkPad:~/youxi/pythonwarrior/liubiantao-beginner$ pythonwarrior
Welcome to Python Warrior
Starting level 2
- turn 1 -
 --------
|@   s  >|
 --------
Traceback (most recent call last):
  File "/home/liubiantao/youxi/py/bin/pythonwarrior", line 20, in <module>
    runner.run()
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/runner.py", line 19, in run
    self.game.start()
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/game.py", line 32, in start
    self.play_normal_mode()
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/game.py", line 71, in play_normal_mode
    self.play_current_level()
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/game.py", line 76, in play_current_level
    self.current_level().play()
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/level.py", line 65, in play
    unit.prepare_turn()
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/units/base.py", line 77, in prepare_turn
    self.play_turn(self.current_turn)
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/units/warrior.py", line 20, in play_turn
    return self.player().play_turn(turn)
  File "/home/liubiantao/youxi/py/local/lib/python2.7/site-packages/pythonwarrior/units/warrior.py", line 26, in player
    import player
  File "./player.py", line 3
    if warrior.feel().is_empty()
                               ^
SyntaxError: invalid syntax
```

Here's python.py 

```
class Player(object):
    def play_turn(self, warrior):
        if warrior.feel().is_empty()
            warrior.walk_()
        else
            warrior.attack_()
```

I just starting learn python,is this my fault?

**Comment by liubiantao** [comment]
I lost : symbol .

But in your README , the code without : symbol

Here is a simple example which will instruct the warrior to attack if he feels an enemy, otherwise he will walk forward.

```
class Player(object):
  def play_turn(self, warrior):
    if warrior.feel().is_enemy()
      warrior.attack_()
    else
      warrior.walk_()
```

**Comment by arbylee** [comment]
Thank you for bringing this to my attention, and I'm sorry for the confusion that must have caused.  I've updated the doc with the missing colons
