### ISSUE TITLE
AttributeError: 'Turn' object has no attribute 'feel'

### ISSUE THREAD

**Issue by aardvarq** [arbylee/python-warrior#5]
Hi there, trying to run this with the default sample code:

```
class Player(object):
    def play_turn(self, warrior):
        if warrior.feel().is_enemy():
            warrior.attack_()
        else:
            warrior.walk_()
```

and getting this output:

```
$ pythonwarrior
Welcome to Python Warrior
[1] Roland - beginner - level 1 - score 0
[2] New Profile
Choose profile by typing the number: 1
Starting level 1
- turn 1 -
 --------
|@      >|
 --------
Traceback (most recent call last):
  File "/usr/bin/pythonwarrior", line 20, in <module>
    runner.run()
  File "/usr/lib/python2.7/site-packages/pythonwarrior/runner.py", line 19, in run
    self.game.start()
  File "/usr/lib/python2.7/site-packages/pythonwarrior/game.py", line 32, in start
    self.play_normal_mode()
  File "/usr/lib/python2.7/site-packages/pythonwarrior/game.py", line 71, in play_normal_mode
    self.play_current_level()
  File "/usr/lib/python2.7/site-packages/pythonwarrior/game.py", line 76, in play_current_level
    self.current_level().play()
  File "/usr/lib/python2.7/site-packages/pythonwarrior/level.py", line 65, in play
    unit.prepare_turn()
  File "/usr/lib/python2.7/site-packages/pythonwarrior/units/base.py", line 77, in prepare_turn
    self.play_turn(self.current_turn)
  File "/usr/lib/python2.7/site-packages/pythonwarrior/units/warrior.py", line 20, in play_turn
    return self.player().play_turn(turn)
  File "./pythonwarrior/roland-beginner/player.py", line 3, in play_turn
    if warrior.feel().is_enemy():
AttributeError: 'Turn' object has no attribute 'feel'
```

**Comment by aardvarq** [comment]
Ah, I didn't realize all of the capabilities weren't initially exposed. That's what I get for jumping through the README too quickly ;-)
