### ISSUE TITLE
pythonwarrior fails to launch

### ISSUE THREAD

**Issue by rapha8l** [arbylee/python-warrior#7]
Hi,

Maybe it's a bit late for opening an issue an on old repo :)
Though I encountered this : 
```
 pythonwarrior                                                                                                                                                                     ⎈ no config
Traceback (most recent call last):
  File "/usr/sbin/pythonwarrior", line 16, in <module>
    from pythonwarrior import runner
  File "/usr/lib/python3.8/site-packages/pythonwarrior/runner.py", line 4, in <module>
    from pythonwarrior.game import Game
  File "/usr/lib/python3.8/site-packages/pythonwarrior/game.py", line 5, in <module>
    from pythonwarrior.level import Level
  File "/usr/lib/python3.8/site-packages/pythonwarrior/level.py", line 5, in <module>
    from pythonwarrior.level_loader import LevelLoader
  File "/usr/lib/python3.8/site-packages/pythonwarrior/level_loader.py", line 12, in <module>
    from pythonwarrior.units.warrior import Warrior
  File "/usr/lib/python3.8/site-packages/pythonwarrior/units/warrior.py", line 36
    print "earns %d points" % points
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("earns %d points" % points)?
```
Thanks

**Comment by JeffSolo** [comment]
@rapha8l I assume you're running Python 3, but pythonwarrior only supports Python 2. Check out PR #6. You can install the fork with the changes: `pip install git+git://github.com/schneiderfelipe/python-warrior`

**Comment by rapha8l** [comment]
Thanks !
Have a nice day
